config/routes.rb
Capricornus::Application.routes.draw do
  devise_for :users
  resources :estimates

  resources :invoices do
    put ':invoice_id/journals', to: "journals#update_all", on: :collection, as: 'update_journals'
    get 'export_pdf'
  end

  get 'calendar', to: 'journals#calendar', as: 'calendar'

  resources :journals, except: [:index] do
    get ':year/:month', to: :index, on: :collection, as: 'monthly', constraints: {year: /\d+/, month: /\d+/}
    resources :costs
  end

  resources :banks

  resources :customers

  resources :companies

  resources :users

  root 'journals#calendar'

  

end

app/models/estimate.rb
class Estimate < ActiveRecord::Base
  has_many :journals
  belongs_to :customer
end

app/controllers/estimates_controller.rb
class EstimatesController < ApplicationController
  before_action :set_estimate, only: [:show, :edit, :update, :destroy]

  # GET /estimates
  # GET /estimates.json
  def index
    @estimates = Estimate.all
  end

  # GET /estimates/1
  # GET /estimates/1.json
  def show
  end

  # GET /estimates/new
  def new
    @estimate = Estimate.new
  end

  # GET /estimates/1/edit
  def edit
  end

  # POST /estimates
  # POST /estimates.json
  def create
    @estimate = Estimate.new(estimate_params)

    respond_to do |format|
      if @estimate.save
        format.html { redirect_to @estimate, notice: '見積が登録されました。' }
        format.json { render action: 'show', status: :created, location: @estimate }
      else
        format.html { render action: 'new' }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estimates/1
  # PATCH/PUT /estimates/1.json
  def update
    respond_to do |format|
      if @estimate.update(estimate_params)
        format.html { redirect_to @estimate, notice: '見積が更新されました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @estimate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estimates/1
  # DELETE /estimates/1.json
  def destroy
    @estimate.destroy
    respond_to do |format|
      format.html { redirect_to estimates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estimate
      @estimate = Estimate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estimate_params
      params.require(:estimate).permit(:number, :title, :deadline, :requirement, :customer_id, :memo, :summary)
    end
end

app/helpers/estimates_helper.rb
module EstimatesHelper
end

app/views/estimates/_form.html.erb
<%= form_for(@estimate) do |f| %>
  <% if @estimate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estimate.errors.count, "error") %> prohibited this estimate from being saved:</h2>

      <ul>
      <% @estimate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :requirement %><br>
    <%= f.text_field :requirement %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area :memo %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.number_field :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estimates/edit.html.erb
<h1>Editing estimate</h1>

<%= render 'form' %>

<%= link_to 'Show', @estimate %> |
<%= link_to 'Back', estimates_path %>

app/views/estimates/index.html.erb
<h1>Listing estimates</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Title</th>
      <th>Deadline</th>
      <th>Requirement</th>
      <th>Customer</th>
      <th>Memo</th>
      <th>Summary</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @estimates.each do |estimate| %>
      <tr>
        <td><%= estimate.number %></td>
        <td><%= estimate.title %></td>
        <td><%= estimate.deadline %></td>
        <td><%= estimate.requirement %></td>
        <td><%= estimate.customer_id %></td>
        <td><%= estimate.memo %></td>
        <td><%= estimate.summary %></td>
        <td><%= link_to 'Show', estimate %></td>
        <td><%= link_to 'Edit', edit_estimate_path(estimate) %></td>
        <td><%= link_to 'Destroy', estimate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estimate', new_estimate_path %>

app/views/estimates/new.html.erb
<h1>New estimate</h1>

<%= render 'form' %>

<%= link_to 'Back', estimates_path %>

app/views/estimates/show.html.erb
<p>
  <strong>Number:</strong>
  <%= @estimate.number %>
</p>

<p>
  <strong>Title:</strong>
  <%= @estimate.title %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @estimate.deadline %>
</p>

<p>
  <strong>Requirement:</strong>
  <%= @estimate.requirement %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @estimate.customer_id %>
</p>

<p>
  <strong>Memo:</strong>
  <%= @estimate.memo %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @estimate.summary %>
</p>

<%= link_to 'Edit', edit_estimate_path(@estimate) %> |
<%= link_to 'Back', estimates_path %>