config/routes.rb
Capricornus::Application.routes.draw do
  devise_for :users
  resources :estimates

  resources :invoices do
    put ':invoice_id/journals', to: "journals#update_all", on: :collection, as: 'update_journals'
    get 'export_pdf'
  end

  get 'calendar', to: 'journals#calendar', as: 'calendar'

  resources :journals, except: [:index] do
    get ':year/:month', to: :index, on: :collection, as: 'monthly', constraints: {year: /\d+/, month: /\d+/}
    resources :costs
  end

  resources :banks

  resources :customers

  resources :companies

  resources :users

  root 'journals#calendar'

  

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  has_many :journals, :dependent => :destroy
  has_many :costs, through: :journals
  belongs_to :customer

  validates :ask_on, :deadline, :customer_id, presence: true

  scope :unfinished_payment, ->(){ where("cancel IS NULL OR cancel = ?", false).where("payment IS NULL OR payment = ?", false) }

  def update_summary
    summary = costs.map{|c| c.count * c.unit_price}.inject(:+)
    update_attributes(summary: summary)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  def export_pdf
    @invoice = Invoice.find(params[:invoice_id])
    render params[:invoice]
  end

  # GET /invoices
  # GET /invoices.json
  def index
    ongoing_invoices = Invoice.unfinished_payment
    @invoices = if params[:customer].present? && params[:ongoing] == "true"
                  ongoing_invoices.where(customer_id: params[:customer].to_i)
                elsif params[:ongoing] == "true"
                  ongoing_invoices
                else
                  Invoice.all
                end
    respond_to do |format|
      format.html
      format.json { render json: @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @journals = @invoice.journals.order("start_at")
    @alone_journals = Journal.where("invoice_id IS NULL").order("start_at")
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: '請求書が登録されました。' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: '請求書が更新されました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:number, :ask_on, :deadline, :customer_id, :memo, :summary, :payment)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
  def download_ok?(invoice)
    invoice.costs.present? ? true : false
  end
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div class="alert alert-danger">
      <h4><em>足りないところがあるようです・・・。</em></h4>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <tr>
      <th><%= f.label :ask_on %></th>
      <td><%= f.text_field :ask_on, class: "pick_date form-control", size: "10" %></td>
    </tr>
    <tr>
      <th><%= f.label :deadline %></th>
      <td><%= f.text_field :deadline, class: "pick_date form-control", size: "10" %></td>
    </tr>
    <tr>
      <th><%= f.label :customer_id %></th>
      <td><%= f.select :customer_id, Customer.all.map{|c| [c.name, c.id]} %></td>
    </tr>
    <tr>
      <th><%= f.label :payment %></th>
      <td><%= f.check_box :payment %></td>
    </tr>
    <tr>
      <th><%= f.label :memo %></th>
      <td><%= f.text_area :memo, class: "form-control" %></td>
    </tr>
    <tr>
      <th><%= f.submit class: "btn btn-primary btn-sm" %></th>
      <td>&nbsp;</td>
    </tr>
  </table>
<% end %>

app/views/invoices/_journal_cost_table.html.erb
      <% if journal.costs.present? %>
        <% journal.costs.each do |cost| %>
          <tr>
            <td><%=journal.start_at.try(:strftime, "%Y-%m-%d") %></td>
            <td>
              <% if cost.unit == "dai" %>
                交通費
              <% else %>
                <%=journal.content %>
              <% end %>
            </td>
            <td><%= t(cost.unit) %></td>
            <td><%= number_to_currency cost.unit_price, :precision => 0, :unit => "円" %></td>
            <td><%= cost.count %></td>
            <td><%= number_to_currency (cost.count || 0) * (cost.unit_price || 0), :precision => 0, :unit => "円" %></td>
            <% case state %>
            <% when "show" then %>
              <td><%= link_to '詳細', journal, class: "btn btn-primary btn-xs" %></td>
            <% when "edit" then %>
              <td><%= check_box_tag 'belong_journal_ids[]', journal.id, 1 %></td>
            <% else %>
              <td><%= check_box_tag 'alone_journal_ids[]', journal.id %></td>
            <% end %>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td><%=journal.start_at.try(:strftime, "%Y-%m-%d") %></td>
          <td><%=journal.content %></td>
          <td colspan="5">ここから請求項目を追加できます。&nbsp;<%= link_to "追加", new_journal_cost_path(journal), class: "btn btn-danger btn-xs" %></td>
        </tr>
      <% end %>

app/views/invoices/edit.html.erb
<h3>請求書編集</h3>

<%= render 'form' %>

<%= link_to 'キャンセル', @invoice %>

app/views/invoices/index.html.erb
<h2>請求書&nbsp;
  <% if params[:ongoing] == "true" %>
    <%= link_to '請求中・予定', invoices_path(ongoing: true), class: "btn btn-primary disabled", id: "invoices_ongoing" %>
    <%= link_to 'すべて', invoices_path, class: "btn btn-default", id: "invoices_all" %>
  <% else %>
    <%= link_to '請求中・予定', invoices_path(ongoing: true), class: "btn btn-default", id: "invoices_ongoing" %>
    <%= link_to 'すべて', invoices_path, class: "btn btn-primary disabled", id: "invoices_all" %>
  <% end %>
</h2>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>番号</th>
      <th>取引先</th>
      <th>請求日</th>
      <th>期限</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= sprintf "%05d", invoice.id %></td>
        <td><%= invoice.customer.try(:name) %></td>
        <td><%= invoice.ask_on %></td>
        <td><%= invoice.deadline %></td>
        <td><%= link_to '詳細', invoice, class: "btn btn-primary btn-sm" %></td>
        <td>
          <% if download_ok?(invoice) %>
            <%= link_to 'ダウンロード', invoice_export_pdf_path(invoice, format: :pdf), class: "btn btn-danger btn-sm" %>
          <% else %>
            詳細で請求項目を追加してください。
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規作成', new_invoice_path, class: "btn btn-danger btn-sm" %>

app/views/invoices/new.html.erb
<h3>請求書入力</h3>

<%= render 'form' %>

<%= link_to 'キャンセル', invoices_path(ongoing: true) %>

app/views/invoices/show.html.erb
<div id="invoice_edit_title" style="display:none">
  <h3 class="text-danger"><em>請求書編集中</em></h3>
</div>
<h3>
  請求書詳細
  &nbsp;&nbsp;
  <%= link_to '編集', edit_invoice_path(@invoice), class: "btn btn-danger btn-sm" %>
  &nbsp;&nbsp;
  <% if download_ok?(@invoice) %>
    <%= link_to 'ダウンロード', invoice_export_pdf_path(@invoice, format: :pdf), class: "btn btn-danger btn-sm pull-right" %>
  <% end %>
</h3>

<div class="panel panel-default">
  <div class="panel-heading">
    <strong><%= @invoice.customer.try(:name) %>様宛&nbsp;&nbsp;<%= @invoice.ask_on %>請求分</strong>
    <% if @invoice.payment != true %>
      <%= link_to invoice_path(@invoice), method: :delete, data: { confirm: '関連した日誌もすべて削除しますが、よろしいですか？' }, class: "pull-right" do %><span class="glyphicon glyphicon-remove text-danger"></span><% end %>
    <% end %>
  </div>
  <table class="table table-bordered">
    <tr>
      <th>番号</th>
      <td><%= sprintf "%05d", @invoice.id %></td>
    </tr>
    <tr>
      <th>取引先</th>
      <td><%= @invoice.customer.try(:name) %></td>
    </tr>
    <tr>
      <th>請求日</th>
      <td><%= @invoice.ask_on %></td>
    </tr>
    <tr>
      <th>支払期限</th>
      <td><%= @invoice.deadline %></td>
    </tr>
    <tr>
      <th>合計額</th>
      <td><%= number_to_currency @invoice.summary, :precision => 0, :unit => "円" %></td>
    </tr>
    <tr>
      <th>支払済</th>
      <td>
        <% if @invoice.payment == true %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>キャンセル</th>
      <td><%= @invoice.cancel %></td>
    </tr>
    <tr>
      <th>備考</th>
      <td><%= @invoice.memo %></td>
    </tr>
  </table>
</div>

<div id="journal_view_area">
  <table class="table table-bordered bottom-no-margin">
    <tr class="active">
      <th>日付</th>
      <th>内容</th>
      <th>単位</th>
      <th>単価</th>
      <th>数量</th>
      <th>金額</th>
      <th>&nbsp;</th>
    </tr>
    <% @journals.each do |journal| %>
      <%= render 'journal_cost_table', journal: journal, state: "show" %>
    <% end %>
  </table>
</div>

<div id="journal_add_area" style="display:none">

<%= form_for(@invoice, method: :put, url: update_journals_invoices_path(@invoice)) do |f| %>
  <table class="table table-bordered bottom-no-margin">
    <tr class="active">
      <th>日付</th>
      <th>内容</th>
      <th>単位</th>
      <th>単価</th>
      <th>数量</th>
      <th>金額</th>
      <th>要請求</th>
    </tr>
    <% @journals.each do |journal| %>
      <%= render 'journal_cost_table', journal: journal, state: "edit" %>
    <% end %>

    <% @alone_journals.each do |journal| %>
      <%= render 'journal_cost_table', journal: journal, state: "add" %>
    <% end %>
  </table>

</div>

<% if @invoice.payment != true && download_ok?(@invoice) %>
  <%= link_to '請求内容編集', "javascript:void(0)", class: "btn btn-danger btn-sm pull-right", id: "open_journal_add_area" %>
<% end %>

<div id="close_journal_add_area" style="display:none" class="pull-right">
<%= link_to 'キャンセル', "javascript:void(0)" %>&nbsp;or&nbsp;
<%= f.submit '更新', class: "btn btn-primary btn-sm" %>
</div>
<% end %>

<div>&nbsp;</div>