config/routes.rb
Capricornus::Application.routes.draw do
  devise_for :users
  resources :estimates

  resources :invoices do
    put ':invoice_id/journals', to: "journals#update_all", on: :collection, as: 'update_journals'
    get 'export_pdf'
  end

  get 'calendar', to: 'journals#calendar', as: 'calendar'

  resources :journals, except: [:index] do
    get ':year/:month', to: :index, on: :collection, as: 'monthly', constraints: {year: /\d+/, month: /\d+/}
    resources :costs
  end

  resources :banks

  resources :customers

  resources :companies

  resources :users

  root 'journals#calendar'

  

end

app/models/journal.rb
class Journal < ActiveRecord::Base
  has_many   :costs, :dependent => :destroy
  belongs_to :user
  belongs_to :invoice
  belongs_to :estimate
  belongs_to :customer

  before_save :correct_period?
  after_save  :connection_to_invoice, if: -> { !done_connection_to_invoice }

  delegate :payment, to: :invoice, allow_nil: true
  validates :payment, exclusion: {in: [true]}
  validates :start_at, :finish_at, :customer_id, presence: true

  attr_accessor :done_connection_to_invoice

  def self.current_month(date)
    first_time = date.beginning_of_month.to_time
    end_time   = first_time.end_of_month
    Journal.where(start_at: first_time..end_time)
  end

  def connection_to_invoice
    self.done_connection_to_invoice = true
    invoice = Invoice.where(customer_id: customer_id).where("? <= ask_on", start_at.to_date).first
    if invoice.present?
      update_attributes(invoice_id: invoice.id)
    else
      ask_on      = Date.new(start_at.year, start_at.month, Company.all.first.close_day)
      new_invoice = Invoice.new(ask_on: ask_on, deadline: ask_on.end_of_month, customer_id: customer_id)
      new_invoice.save
      update_attributes(invoice_id: new_invoice.id)
    end
  end

  def correct_period?
    if start_at >= finish_at
      errors.add("start_at", "が終業時刻より遅い時間に設定されています。")
      return false
    end
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: [:show, :edit, :update, :destroy]

  def calendar

  end

  # GET /journals
  # GET /journals.json
  def index
    date = params[:month] ? Date.new(params[:year].to_i, params[:month].to_i, 1) : Date.today
    @journals = Journal.current_month(date).order("start_at")

    respond_to do |format|
      format.html
      format.json { render json: @journals }
    end
  end

  # GET /journals/1
  # GET /journals/1.json
  def show
    @costs = @journal.costs
  end

  # GET /journals/new
  def new
    if params[:date]
      (year, month, day) = params[:date].split('-')
      base_start_time  = Time.new(year.to_i, month.to_i, day.to_i, 8, 0)
      base_finish_time = Time.new(year.to_i, month.to_i, day.to_i, 17, 0)
    end

    @journal = Journal.new(start_at: base_start_time, finish_at: base_finish_time)
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals
  # POST /journals.json
  def create
    if params[:journal][:base_id].present?
      base_journal = Journal.find(params[:journal][:base_id])
      journal      = base_journal.attributes.reject{|k, v| k == "id" || k == "created_at" || k == "updated_at"}
      @journal           = Journal.new(journal)
      @journal.start_at  = @journal.start_at + params[:journal][:day_delta].to_i.days
      @journal.finish_at = @journal.finish_at + params[:journal][:day_delta].to_i.days
      @journal.save

      base_costs = base_journal.costs
      if base_costs.present?
        base_costs.each do |base_cost|
          cost     = base_cost.attributes.reject{|k, v| k == "id" || k == "created_at" || k == "updated_at"}
          new_cost            = Cost.new(cost)
          new_cost.journal_id = @journal.id
          new_cost.save
        end
      end

      respond_to do |format|
        format.json { render action: 'show'}
      end
      return
    else
      @journal = Journal.new(journal_params)

      respond_to do |format|
        if @journal.save
          format.html { redirect_to @journal, notice: '日誌が登録されました。' }
        else
          format.html { render action: 'new' }
        end
      end
    end
  end

  # PATCH/PUT /journals/1
  # PATCH/PUT /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to @journal, notice: '日誌が更新されました。' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_all
    @invoice  = Invoice.find(params[:invoice_id].to_i)
    @journals = @invoice.journals

    delete_journal_ids = @journals.map{|j| j.id} - (params[:belong_journal_ids] || [nil]).map{|s| s.to_i}
    if delete_journal_ids.present?
      delete_journal_ids.each do |journal_id|
        journal = Journal.find(journal_id)
        journal.update_attributes(invoice_id: nil)
      end
    end

    if params[:alone_journal_ids].present?
      params[:alone_journal_ids].map{|s| s.to_i}.each do |journal_id|
        journal = Journal.find(journal_id)
        journal.update_attributes(invoice_id: @invoice.id)
      end
    end

    @invoice.update_summary #need_test!

    redirect_to invoice_path(params[:invoice_id])
  end

  # DELETE /journals/1
  # DELETE /journals/1.json
  def destroy
    @journal.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def journal_params
      params.require(:journal).permit(:start_at, :finish_at, :content, :city, :customer_id, :complete, :invoice_id, :user_id)
    end
end

app/helpers/journals_helper.rb
module JournalsHelper
  def next_month
    params[:month] ?
      Date.new(params[:year].to_i, params[:month].to_i, 1) + 1.month : Date.today + 1.month
  end

  def prev_month
    params[:month] ?
      Date.new(params[:year].to_i, params[:month].to_i, 1) - 1.month : Date.today - 1.month
  end

  def edit_ok(journal)
    journal.invoice_id.present? ? journal.invoice.payment != true : true
  end
end

app/views/journals/_form.html.erb
<%= form_for(@journal) do |f| %>
  <% if @journal.errors.any? %>
    <div class="alert alert-danger">
      <h4><em>足りないところがあるようです・・・。</em></h4>

      <ul>
      <% @journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="table">
    <tr>
      <th><%= f.label :start_at %></th>
      <td><%= f.text_field :start_at, {value: f.object.start_at.try("strftime", "%F %H:%M"), class: "pick_datetime_5 form-control", size: "10"} %></td>
    </tr>
    <tr>
      <th><%= f.label :finish_at %></th>
      <td><%= f.text_field :finish_at, {value: f.object.finish_at.try("strftime", "%F %H:%M"), class: "pick_datetime_5 form-control", size: "10"} %></td>
    </tr>
    <tr>
      <th><%= f.label :content %></th>
      <td><%= f.text_field :content, class: "form-control" %></td>
    </tr>
    <tr>
      <th><%= f.label :city %></th>
      <td><%= f.text_field :city, class: "form-control" %></td>
    </tr>
    <tr>
      <th><%= f.label :customer_id %></th>
      <td><%= f.select :customer_id, Customer.all.map{|c| [c.name, c.id]}, {} %></td>
    </tr>
    <tr>
      <th><%= f.label :complete %></th>
      <td><%= f.check_box :complete %></td>
    </tr>
    <% if request.path_parameters[:action] == "edit"%>
      <tr>
        <th><%= f.label :invoice_id %></th>
        <td class="invoice_id_area">
          請求日&nbsp;<%= f.select :invoice_id, Invoice.unfinished_payment.where(customer_id: @journal.customer_id).map{|c| [c.ask_on, c.id]}, {include_blank: '保留'}, class: "invoice_id_selector" %>
        </td>
      </tr>
    <% end %>
    <tr>
      <th><%= f.submit class: "btn btn-primary btn-sm" %></th>
      <td>&nbsp;</td>
    </tr>
  </table>
  <%= f.hidden_field :user_id, value: current_user.id %>
<% end %>

app/views/journals/calendar.html.erb
<div id="calendar"></div>

app/views/journals/edit.html.erb
<h3>日誌編集</h3>

<%= render 'form' %>

<%= link_to 'キャンセル', @journal %>

app/views/journals/index.html.erb
<div style="padding-top: 20px;">
  <table class="fc-header" style="width: 100%">
    <tbody>
      <tr>
        <td class="fc-header-left">
          <span class="fc-header-title">
            <h2><%= params[:year] || Date.today.year %>年<%= params[:month]  || Date.today.month %>月</h2>
          </span>
        </td>
        <td class="fc-header-center"></td>
        <td class="fc-header-right">
          <%= link_to monthly_journals_path(prev_month.year, prev_month.month) do %><span class="fc-button fc-button-prev fc-state-default fc-corner-left" unselectable="on" style="-moz-user-select: none;"><span class="fc-text-arrow">‹</span></span><% end %><%= link_to monthly_journals_path(next_month.year, next_month.month) do %><span class="fc-button fc-button-next fc-state-default fc-corner-right" unselectable="on" style="-moz-user-select: none;"><span class="fc-text-arrow">›</span></span><% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>日時</th>
      <th>場所</th>
      <th>取引先</th>
      <th>内容</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <tbody>
    <% @journals.each do |journal| %>
      <tr>
        <td><%= journal.start_at.try(:strftime, "%Y-%m-%d %H:%M") %>〜</td>
        <td><%= journal.city %></td>
        <td><%= journal.customer.try(:name) %></td>
        <td><%= journal.content %></td>
        <td><%= link_to '詳細', journal, class: "btn btn-primary btn-sm" %></td>
        <td>
          <% if edit_ok(journal) %>
            <%= link_to '編集', edit_journal_path(journal), class: "btn btn-danger btn-sm" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '日誌入力', new_journal_path, class: "btn btn-danger btn-sm" %>

app/views/journals/new.html.erb
<h3>日誌入力</h3>

<%= render 'form' %>

<%= link_to 'キャンセル', root_path %>

app/views/journals/show.html.erb
<h3>日誌詳細&nbsp;&nbsp;
  <% if edit_ok(@journal) %>
    <%= link_to '編集', edit_journal_path(@journal), class: "btn btn-danger btn-sm" %>
  <% end %>
</h3>

<div class="panel panel-default">
  <div class="panel-heading">
    <strong><%= @journal.start_at.try(:strftime, "%Y-%m-%d") %></strong>
    <% if edit_ok(@journal) %>
      <%= link_to journal_path(@journal), method: :delete, data: { confirm: 'Are you sure?' }, class: "pull-right" do %><span class="glyphicon glyphicon-remove text-danger"></span><% end %>
    <% end %>
  </div>
  <table class="table table-bordered">
    <tr>
      <th>始業時刻</th>
      <td><%= @journal.start_at.try(:strftime, "%Y-%m-%d %H:%M") %></td>
    </tr>
    <tr>
      <th>終業時刻</th>
      <td><%= @journal.finish_at.try(:strftime, "%Y-%m-%d %H:%M") %></td>
    </tr>
    <tr>
      <th>内容</th>
      <td><%= @journal.content %></td>
    </tr>
    <tr>
      <th>場所</th>
      <td><%= @journal.city %></td>
    </tr>
    <tr>
      <th>取引先</th>
      <td><%= @journal.customer.try(:name) %></td>
    </tr>
    <tr>
      <th>作業完了</th>
      <td>
        <% if @journal.complete == true %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>請求書</th>
      <td>
        <% if @journal.invoice_id.present? %>
          請求日&nbsp;<%= @journal.invoice.ask_on.try(:strftime, "%Y-%m-%d") %>&nbsp;&nbsp;
          <%= link_to '詳細', invoice_path(@journal.invoice_id), class: "btn btn-primary btn-xs" %>
        <% else %>
          保留中
        <% end %>
      </td>
    </tr>
    <tr>
      <th>実施者</th>
      <td><%= @journal.user.try(:name) %></td>
    </tr>
  </table>
</div>

<table class="table table-bordered bottom-no-margin">
  <tr class="active">
    <th>単位</th>
    <th>単価</th>
    <th>数量</th>
    <th>金額</th>
    <% if edit_ok(@journal) %>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    <% end %>
  </tr>
  <% @costs.each do |cost| %>
  <tr>
    <td><%= t(cost.unit) %></td>
    <td><%= number_to_currency cost.unit_price, :precision => 0, :unit => "円" %></td>
    <td><%= cost.count %></td>
    <td><%= number_to_currency (cost.count || 0) * (cost.unit_price || 0), :precision => 0, :unit => "円" %></td>
    <% if edit_ok(@journal) %>
      <td><%= link_to journal_cost_path(@journal, cost), method: :delete, data: { confirm: 'Are you sure?' } do %><span class="glyphicon glyphicon-remove text-danger"></span><% end %></td>
      <td><%= link_to '編集', edit_journal_cost_path(@journal, cost), class: "btn btn-danger btn-xs" %></td>
    <% end %>
  </tr>
  <% end %>
</table>
<% if edit_ok(@journal) %>
  <%= link_to '項目追加', new_journal_cost_path(@journal), class: "btn btn-danger btn-sm pull-right" %>
<% end %>

<div>&nbsp;</div>