config/routes.rb
Capricornus::Application.routes.draw do
  devise_for :users
  resources :estimates

  resources :invoices do
    put ':invoice_id/journals', to: "journals#update_all", on: :collection, as: 'update_journals'
    get 'export_pdf'
  end

  get 'calendar', to: 'journals#calendar', as: 'calendar'

  resources :journals, except: [:index] do
    get ':year/:month', to: :index, on: :collection, as: 'monthly', constraints: {year: /\d+/, month: /\d+/}
    resources :costs
  end

  resources :banks

  resources :customers

  resources :companies

  resources :users

  root 'journals#calendar'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>Capricornus</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="../../assets/js/html5shiv.js"></script>
  <script src="../../assets/js/respond.min.js"></script>
  <![endif]-->

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Capricornus', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <% date = Date.today %>
          <li><%= link_to '日誌', monthly_journals_path(date.year, date.month) %></li>
          <li><%= link_to '請求書', invoices_path(ongoing: true) %></li>
          <li><%#= link_to '見積書', estimates_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">myページ<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to '自社設定', companies_path %></li>
              <li><%= link_to '銀行設定', banks_path %></li>
              <li><%= link_to '取引先設定', customers_path %></li>
              <li><%= link_to 'ユーザー設定', users_path %></li>
            </ul>
          </li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        </ul>
      <% end %>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <% if notice %>
          <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <%= notice %>
          </div>
        <% end %>
        <%= yield %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <footer>
          <br />
          Development by <a href="https://github.com/satomicchy/Capricornus">satomicchy</a>
        </footer>
      </div>
    </div>
  </div>

</body>
</html>